### ISSUE TITLE
Url link broken

### ISSUE THREAD

**Issue by ariedeleen** [adriannuta/SphinxFacetingExample#5]
Hello Adrian,

There where examples of faceted search with the old and the new sphinx FACET feature.
Blog post: http://sphinxsearch.com/blog/2014/05/22/the-facet-feature/

But the link is broken. http://sphinxdemos.adriannuta.com/SphinxFacetingExample/
The example here in Github uses the old way with Group BY in staid of FACET
Is there an example that uses the the sphinx facet feature.

thanx in advance,

Arie

**Comment by adriannuta** [comment]
Hi, facetpricesnew.php uses FACET. I also updated the link to the demos (they are now hosted at demos.sphinxsearch.com).
