### ISSUE TITLE
How does this use Sphinx?

### ISSUE THREAD

**Issue by syrsly** [adriannuta/SphinxFacetingExample#9]
From what I can tell, it only utilizes PDO and prepared statements.

**Comment by adriannuta** [comment]
Sphinx/Manticore have a mysql-compatible protocol called SphinxQL, which is also the recommended way for connecting, 9306 is the default port for it.
It works with  any MySQL client/connector/library, including PDO.

```
$ln_sph = new PDO( 'mysql:host=127.0.0.1;port=9306' );
```

**Comment by syrsly** [comment]
Sounds interesting! I did not know this port information at all. I always used an api file. Thanks for the heads up.
